[project]
name = "pdmlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pvlib>=0.13.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "pytest>=8.4.1",
    "taskipy>=1.14.1",
    "build>=1.2.1",
]

[tool.taskipy.tasks]
start = "bash scripts/start.sh"
test = "bash scripts/test.sh"
lint = "bash scripts/lint.sh"
lint-format = "bash scripts/lint-format.sh"
